// Code generated by mockery v2.50.4. DO NOT EDIT.

package mocks

import (
	models "github.com/ngikut-project-sprint/GoGoManager/internal/models"
	mock "github.com/stretchr/testify/mock"

	utils "github.com/ngikut-project-sprint/GoGoManager/internal/utils"
)

// ManagerService is an autogenerated mock type for the ManagerService type
type ManagerService struct {
	mock.Mock
}

type ManagerService_Expecter struct {
	mock *mock.Mock
}

func (_m *ManagerService) EXPECT() *ManagerService_Expecter {
	return &ManagerService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: email, password
func (_m *ManagerService) Create(email string, password string) (int, *utils.GoGoError) {
	ret := _m.Called(email, password)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int
	var r1 *utils.GoGoError
	if rf, ok := ret.Get(0).(func(string, string) (int, *utils.GoGoError)); ok {
		return rf(email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) int); ok {
		r0 = rf(email, password)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string, string) *utils.GoGoError); ok {
		r1 = rf(email, password)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GoGoError)
		}
	}

	return r0, r1
}

// ManagerService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ManagerService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - email string
//   - password string
func (_e *ManagerService_Expecter) Create(email interface{}, password interface{}) *ManagerService_Create_Call {
	return &ManagerService_Create_Call{Call: _e.mock.On("Create", email, password)}
}

func (_c *ManagerService_Create_Call) Run(run func(email string, password string)) *ManagerService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *ManagerService_Create_Call) Return(_a0 int, _a1 *utils.GoGoError) *ManagerService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ManagerService_Create_Call) RunAndReturn(run func(string, string) (int, *utils.GoGoError)) *ManagerService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with no fields
func (_m *ManagerService) GetAll() ([]models.Manager, *utils.GoGoError) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Manager
	var r1 *utils.GoGoError
	if rf, ok := ret.Get(0).(func() ([]models.Manager, *utils.GoGoError)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Manager); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Manager)
		}
	}

	if rf, ok := ret.Get(1).(func() *utils.GoGoError); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GoGoError)
		}
	}

	return r0, r1
}

// ManagerService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type ManagerService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *ManagerService_Expecter) GetAll() *ManagerService_GetAll_Call {
	return &ManagerService_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *ManagerService_GetAll_Call) Run(run func()) *ManagerService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ManagerService_GetAll_Call) Return(_a0 []models.Manager, _a1 *utils.GoGoError) *ManagerService_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ManagerService_GetAll_Call) RunAndReturn(run func() ([]models.Manager, *utils.GoGoError)) *ManagerService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function with given fields: email
func (_m *ManagerService) GetByEmail(email string) (*models.Manager, *utils.GoGoError) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *models.Manager
	var r1 *utils.GoGoError
	if rf, ok := ret.Get(0).(func(string) (*models.Manager, *utils.GoGoError)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Manager); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Manager)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *utils.GoGoError); ok {
		r1 = rf(email)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GoGoError)
		}
	}

	return r0, r1
}

// ManagerService_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type ManagerService_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - email string
func (_e *ManagerService_Expecter) GetByEmail(email interface{}) *ManagerService_GetByEmail_Call {
	return &ManagerService_GetByEmail_Call{Call: _e.mock.On("GetByEmail", email)}
}

func (_c *ManagerService_GetByEmail_Call) Run(run func(email string)) *ManagerService_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ManagerService_GetByEmail_Call) Return(_a0 *models.Manager, _a1 *utils.GoGoError) *ManagerService_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ManagerService_GetByEmail_Call) RunAndReturn(run func(string) (*models.Manager, *utils.GoGoError)) *ManagerService_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *ManagerService) GetByID(id int) (*models.Manager, *utils.GoGoError) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Manager
	var r1 *utils.GoGoError
	if rf, ok := ret.Get(0).(func(int) (*models.Manager, *utils.GoGoError)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Manager); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Manager)
		}
	}

	if rf, ok := ret.Get(1).(func(int) *utils.GoGoError); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GoGoError)
		}
	}

	return r0, r1
}

// ManagerService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ManagerService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int
func (_e *ManagerService_Expecter) GetByID(id interface{}) *ManagerService_GetByID_Call {
	return &ManagerService_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *ManagerService_GetByID_Call) Run(run func(id int)) *ManagerService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *ManagerService_GetByID_Call) Return(_a0 *models.Manager, _a1 *utils.GoGoError) *ManagerService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ManagerService_GetByID_Call) RunAndReturn(run func(int) (*models.Manager, *utils.GoGoError)) *ManagerService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: manager
func (_m *ManagerService) Update(manager *models.Manager) *utils.GoGoError {
	ret := _m.Called(manager)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *utils.GoGoError
	if rf, ok := ret.Get(0).(func(*models.Manager) *utils.GoGoError); ok {
		r0 = rf(manager)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.GoGoError)
		}
	}

	return r0
}

// ManagerService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ManagerService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - manager *models.Manager
func (_e *ManagerService_Expecter) Update(manager interface{}) *ManagerService_Update_Call {
	return &ManagerService_Update_Call{Call: _e.mock.On("Update", manager)}
}

func (_c *ManagerService_Update_Call) Run(run func(manager *models.Manager)) *ManagerService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Manager))
	})
	return _c
}

func (_c *ManagerService_Update_Call) Return(_a0 *utils.GoGoError) *ManagerService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ManagerService_Update_Call) RunAndReturn(run func(*models.Manager) *utils.GoGoError) *ManagerService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewManagerService creates a new instance of ManagerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManagerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ManagerService {
	mock := &ManagerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
