// Code generated by mockery v2.50.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EmailValidator is an autogenerated mock type for the EmailValidator type
type EmailValidator struct {
	mock.Mock
}

type EmailValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *EmailValidator) EXPECT() *EmailValidator_Expecter {
	return &EmailValidator_Expecter{mock: &_m.Mock}
}

// ValidateEmail provides a mock function with given fields: email
func (_m *EmailValidator) ValidateEmail(email string) error {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for ValidateEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EmailValidator_ValidateEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateEmail'
type EmailValidator_ValidateEmail_Call struct {
	*mock.Call
}

// ValidateEmail is a helper method to define mock.On call
//   - email string
func (_e *EmailValidator_Expecter) ValidateEmail(email interface{}) *EmailValidator_ValidateEmail_Call {
	return &EmailValidator_ValidateEmail_Call{Call: _e.mock.On("ValidateEmail", email)}
}

func (_c *EmailValidator_ValidateEmail_Call) Run(run func(email string)) *EmailValidator_ValidateEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *EmailValidator_ValidateEmail_Call) Return(_a0 error) *EmailValidator_ValidateEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EmailValidator_ValidateEmail_Call) RunAndReturn(run func(string) error) *EmailValidator_ValidateEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewEmailValidator creates a new instance of EmailValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailValidator {
	mock := &EmailValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
