name: Lint Code

on:
  pull_request:
    branches:
      - main

env:
  GO_VERSION: "1.23.4"

jobs:
  golangcli-lint:
    name: Lint Go Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install golangcli-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.63.4
          echo "::add-path::$(go env GOPATH)/bin" # Ensure it's added to the PATH
          golangcli-lint version

      - name: Run golangcli-lint
        run: |
          golangcli-lint run ./...

      - name: Upload lint report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: golangcli-lint-report
          path: ./golangcli-lint-report.txt
